### ISSUE TITLE
Why are notifications so slow?

### ISSUE THREAD

**Issue by Gatienzo** [TwidereProject/Twidere-Android#1013]
Slow Twitter notifications compared to Hootsuite
Android 601. Samsung over wifi.

**Comment by tdemin** [comment]
Twidere doesn't use a push notification server. And the battery saving mechanisms of Android M (same goes for Nougat and Oreo) suspend the app until it receives a push notification. As soon as Twidere doesn't receive any, it's not resumed, so it rarely can check for notifications. That's why notifications are slow.

**Comment by Tedko** [comment]
wont fix this for now. Will focus on other issues we can fix now
