### ISSUE TITLE
 Tracker in Twidere

### ISSUE THREAD

**Issue by meaz** [TwidereProject/Twidere-Android#1028]
Hi,

according to this [report](https://reports.exodus-privacy.eu.org/reports/384/), Twidere has the DoubleClick traker. I must admit that I'm kind of disappointed! Would it be possible to remove it? Espcially when one download Twidere from fdroid...

Thanks

**Comment by mariotaku** [comment]
Twidere added Admob ads since 3.7.0. These ads are part of "Promotion reward" feature - Users enable this feature explicitly to use enhanced features for free, in exchange of seeing some kind of ads (banners at present). This feature can be turned off anytime in settings.

Good news is, since ads and Google Play Services are not FOSS, they are completely removed in F-Droid version, which means F-Droid version doesn't contain any trackers or ads. (Though it may lack of enhanced features).

So, if you use Twidere installed from F-Droid, you don't need to worry about any privacy issue.
