### ISSUE TITLE
[Feature Request] Actions tab

### ISSUE THREAD

**Issue by regularlabs** [TwidereProject/Twidere-Android#1032]
Would love to see an extra tab/column type called 'Actions' (or whatever) that will list when people like an RT your tweets. When people start following you. And even - if possible - when they unfollow you. 

There could even be more optional stuff included, like messages when you pass certain amounts of followers (every 100 / 1,000). And when you approach or reach certain amounts of tweets ("Your next tweet will be your 1000th").

**Comment by orithena** [comment]
Most of the stuff of your first paragraph is already possible, but sadly, not for third-party apps (i.e. non-official apps). You can get around that limitation by using one the official keys when you first authenticate your account in Twidere against twitter. See here: https://gist.github.com/mariotaku/5465786

Unfollows are not made visible by Twitter. You'd need to use your own scripts and database to do that, e.g. with this script: https://github.com/orithena/twitter-follower-report

Your second paragraph would be interesting, I agree on that, but since this data is not directly available without polling the API often (counting would not work reliably, since you still might use Tweetdeck in parallel), implementing it reliably would drain your battery and the rate limit imposed by the Twitter API. Implementing it unreliably would just increase the bug reports and it would be more trouble than it's worth. A better way for that would be a Twitter bot perusing the Streaming API and sending notifications via Tweet/DM to you.

**Comment by regularlabs** [comment]
Thanks for the reply.
I don't quite understand your reply on the first part.

There currently in no 'Activity' tab in Twidere as described.
Will adding the official keys create such a tab? Seems unlikely to me.
I updated the API keys with those from the gist, restarted the app, but do not see anything change in behavior...

Regarding the nr of followers and tweets: does Twidere not already get that info?
When you open the account view (click on your own profile image) you see that information there.
I get that that would require an extra call via the API, but if that happens like once an hour or whatever, won't that be enough? At least for the nr of followers thing.
Number of tweets can probably be binned. I get the that would require constant checking, so undoable.

**Comment by orithena** [comment]
There is an "interactions" tab (or at least, you can add it in the settings -- swipe in from left to see the settings menu). With the official keys, likes and RTs of your tweets, mentions to you and follow notices are shown there. It's a bit limited when you use the default keys. Also, after you changed the keys, you need to do a complete re-login including re-authorization of the app; i.e.: remove your account from Twidere and re-add it. (This is due to a process called OAuth, where you enter your password once to allow the app on your phone to negotiate a cryptographic secret with Twitter for all future use. This secret is saved on your phone; removing your account from twidere removes that secret too. In addition, you can revoke such secrets in your profile settings on Twitter Web.)

Regarding the number of Followers/Tweets: yes, that could be done once an hour or so, but would require loading the whole user profile. Normally, this is only updated on viewing it. I myself would not want my Twitter client to load more stuff than necessary.

Then again, I'm not a Twidere developer, I'm just a user who knows a thing or two about the Twitter API (having written Twitter Bots myself). Therefore, please keep your improvement suggestions coming, even if I tell you why it would not work nicely or why I personally don't like it. In the end, it's the developers choice (and sometimes, his timetables choice) what to implement next.

**Comment by mariotaku** [comment]
@regularlabs Thanks to @orithena 's answer, that is correct. Also please keep in mind that once I finished #1016 , full featured interactions tab may be available to all users. (It needs some configurations though)
