### ISSUE TITLE
Option to REMOVE Compose Button entirely

### ISSUE THREAD

**Issue by vphantom** [TwidereProject/Twidere-Android#104]
I'm not well-versed in Java so I can't attempt this myself, hence this enhancement suggestion. I appreciate the new option to move this button to the right, but it still takes up precious real estate and only scrolls off when moving the timeline the wrong way.  (I read from where I left off towards the present.)  A simple fix would be to add a second toggle option, which would remove this button entirely.  It's redundant with the "Compose" item in the left-hand drawer menu anyway. :)

**Comment by LucPestille** [comment]
I think the option to compose without sliding the right hand draw open is useful, but I agree that the button does get in the way a little bit at the bottom, left or right - it feels like I might accidentally trigger it when scrolling, so I purposefully shorten my swipe down.

Maybe it could be (optionally) moved to the top, as an additional 'tab'?

**Comment by VPhantom** [comment]
Actually my main problem is that the hiding/revealing of the compose buton and the title bar are exactly backwards of what is naturally expected: when we're scrolling towards the top (finger top-down) while catching up chronologically, both are shown, and when we're scrolling into the past (finger down-top, towards older tweets at bottom), they are hidden to give us more room for some reason.

This UI behavior seems to assume that people read the newest tweets first, and catch up with progressively older tweets in reverse order until they see something they remember, like what the Twitter web site itself does (which is crazy - after all these years they still don't save timeline positions and no user seems to care).  That's nuts for someone like me who uses Twitter mostly for news; I make the client remember my timeline position specifically so that I can catch up in chronological order.

So anyway, my work-around is to "over-scroll" by about 1cm, then scroll back up 1cm to make the compose key and title bar disappear, giving me the most screen real estate.  I'd inverse this behavior if I could, but like I said I'm not well-versed here.  Java I could work with, but I know nothing of the massive Android API.

**Comment by vphantom** [comment]
The latest update of Twidere I received, 3.1.4.2, completely solves this by hiding the tabs _and_ the pesky compose button when we're scrolling to catch up to the present. :smiley:
