### ISSUE TITLE
Other action when clicking on activity (likes & retweets)

### ISSUE THREAD

**Issue by regularlabs** [TwidereProject/Twidere-Android#1045]
Under the Activity tab you can see stuff like mentions, likes, retweets and follows.

However, with the likes and retweets, when clicking on the entry, it brings you to the account of that user. Not o the tweet it concerns.

Can this be changed?
Maybe let a click on the user name/avatar still link to the account. But clicking on the rest should open up the message.

**Comment by orithena** [comment]
Strange. When I tap on a like/RT notification, i.e. one that looks like this:
![screenshot_20171220-170839 2](https://user-images.githubusercontent.com/2767109/34216484-c9cf16ba-e5a8-11e7-976b-2a0536a1c42d.png)
... it takes me to an intermediate dialog that shows the concerning tweet(s) and user(s) that are complicit in that notification:
![screenshot_20171220-170921 2](https://user-images.githubusercontent.com/2767109/34216572-fb5f61b2-e5a8-11e7-96fd-22cd2f60b7e4.png)

From there, I can choose between jumping to the tweet displayed in thread context or to each concerned user profile. All working as expected, as I just confirmed.

This intermediate dialog is necessary because multiple notifications might be combined into a single notification (multiple users liking one tweet/RT or multiple tweets/RTs liked by one user).

I also cannot find a setting that might influence the behaviour you describe.

(Using Twitter on Twidere 3.7.3-google on Android 6.1.1, having official keys entered manually.)

**Comment by regularlabs** [comment]
Sorry, please ignore. I was all mixed up :)

**Comment by orithena** [comment]
No sweat :)
