### ISSUE TITLE
using github is indirectly supporting fascism

### ISSUE THREAD

**Issue by PaulFree14** [TwidereProject/Twidere-Android#1135]
As many of you propably know, github got bought by microsoft.
Yet there is many to say about microsoft, but I believe it's important to have current events in mind, and how the struggle for free software can be linked with those of others.

That's how resisting becomes more powerfull, when the opressed give visability to each others struggle and take action of solidary.

Microsoft is currently supporting ICE.
Take on that matter also a look at this:
https://boingboing.net/2018/06/20/godwins-law-suspended.html
(myself haven't really made any research on that sybject)

This is a call for directAction in solidarity with anyone being effected by the fascist activities conducted by the US agency ICE.

Since being here on github, we can start to use this proprietary plattform instead of sharing code, colaborating on code and being constructive about coding to use it to exclusivly share informations about microsoft supporting fascism, what it has to do with ones own use of this plattform and deconstructing fascist ideology.

Also start writing issues about this into any other software projects you empathise with
and encourage people to do the same.

Thought their is potential of making a trend out of this, that could damage the trademark github and microsoft and raises more awareness about ICE within the coder scene.

Maybe someone could come up with a much better writing then this one, incl. some more research and possibilities that can be taken to resist ICE in specific or racism in general.

**Comment by mariotaku** [comment]
Posting irrelevant issue on open source project is simply spamming. If you continue posting unrelated topics on my repo, I'll report abuse for that.

**Comment by PaulFree14** [comment]
Mariotaku, this is the moment I will enterily stop doing any promotion for twidere and instead delete it from my phone. 

The issue I created is entirly relevant to your opensource project since your project *is* using github.

And all you do is calling to not disturb your shiny privilidged developer world. 
With you, activly excluding people from the discourse when adressing issues relevant to your opensource project in relation of historical significant current events, you are complicit in taking part of enabeling fascism/racism/mass arrest/murder...


It's like you sayn: 'Ey! Stop asking me to stop with my opensource project indirectly supporting mass detention centers, incl. mass arrest of children and the seperation between them and their parent.'

If you find just anytime in your privilidged life, pls reflect on that.

**Comment by mariotaku** [comment]
LOL, just please go ahead. 

BTW I know (Godwin's law)[https://en.wikipedia.org/wiki/Godwin%27s_law] is real thanks to you. Wish you have a wonderful day fighting with "facism" and "censorship", good luck!

**Comment by annando** [comment]
I would like to say something to this issue: The point is not, **what** had been said, but **how**. I think all open source projects on github should consider moving somewhere else, eventually we at Friendica will move as well. But - from my point of view - it would had been better to simply ask in a polite way - without any activism - if this projects considers moving to some other repository.

P.S.: This is planned to be my only comment on this.

**Comment by kcschan** [comment]
@PaulFree14 
How could you even possibly speak of "......entirly relevant to your opensource project since your project is using github", do you believe you are selfish?

**Comment by PaulFree14** [comment]
>do you believe you are selfish?
I do not made this comment to have any personal gain. I'm not from the US, not being a migrant, and can have access to legal documents. 
If the way I wrote it is an issue...I'm just speaking english since very few years. 
Why the heck should it be about me. It's the topic that is relevant, not my words, not even me. 

>Wish you have a wonderful day fighting with "facism" and "censorship"
facism always starts somewhere. Imprisoning kids and pumping them up with drugs...if the resistance isn't getting strong enough that's where their society is heading towards. 
Adding the facism here in ' ' seems like you being ironic about what's happening through ICE.

And if the issue is here about me, or my framing, I do NOT matter here, but that microsoft bought github, that microsoft is serving ICE with software, that ICE is...(I said it already), that opensource projects use github giving credibility to microsofts 7.5 billion $ investment...etc.

But yes, since you're managing the project it's you who decides what should be seen as relevant to it and what not.

**Comment by PaulFree14** [comment]
Some more statements by godwin that I find to be relavant for this discourse related to the 'godwin law', since mariotaku mentioned it:
https://todon.nl/@paulfree14/100244278402109587

**Comment by mariotaku** [comment]
Most of us DO hate when Microsoft acquired Github. 

However, @PaulFree14, did you ever saw [this statement by Microsoft](https://blogs.microsoft.com/on-the-issues/2018/06/18/microsoft-statement-on-separating-families-at-the-southern-border/)?

You simply spamming on people's repo, forcing them to be on your side, and just say those doesn't agree with you _complicit in taking part of enabling fascism/racism/mass arrest/murder_?

And you think I'm privileged? Risking myself developing Twidere In a [state](https://en.wikipedia.org/wiki/China) that [threatened](https://en.wikipedia.org/wiki/Shadowsocks#Takedown) and [jailed](http://www.scmp.com/news/china/policies-politics/article/2125326/man-jailed-51/2-years-fined-us76000-selling-vpn) developers developing or hosting censorship circumvent tools? 

For god sake could you please stop this slippery slope?

I'm not asking for an apologize. I just want to let you know how **not** to let others agree your opinion.

**Comment by PaulFree14** [comment]
>And you think I'm privileged?

I made assumptions with that I shouldn't. I should have asked instead. But I guess what I actully ment (behind the rage I had) was more to reflect on your privilidges, since I believe we all have some.

I honestly apologize for 'reflect on your privilidged life'. That was manipulative, wrong, offensive....etc.

**Comment by mariotaku** [comment]
My final answer is, no. I currently don't have plan migrating to other open source platforms, since they are technically not stable than Github. 

I do have concerns about freedom of speech being violated since Microsoft is more prone to govt's takedown request, or even possible to hand out user information to whom actively contributing to [anti-censorship tools](https://github.com/shadowsocks) or documents [revealing govt's dirty secrets](https://github.com/programthink/zhao/). When Github & Microsoft doing that, we'll surely do anything helpful like archive those data to prevent them from completely removed.

Just remember, one choosing migrate or not migrate from Github have their own reasons. And we have our own position on political spectrum. But most of us definitely would stand up to defend humanity, not just by moving data from a platform to another.

**Comment by PaulFree14** [comment]
>and just say those doesn't agree with you complicit in taking part of enabling fascism/racism/mass arrest/murder

That I found to be very missleading statment since I made a clear (I hoped so) statement about how I believe it's taking part in enabeling. And yes, there will be propably points I'm wrong about, but I'm not calling someone being part in enabeling fascism when they call me wrong on it. 

About Microsoft's statment:
They are by that taking part in forming a narrative that is about, 'it's only bad because of the seperation'...as in, it's ok to look them up unified. 

more about microsoft:
''Microsoft Removes Mention of ICE Cloud Work After Protests

''On Jan. 24, Tom Keane, a Microsoft executive, wrote a blog post about new contracts with the U.S. Air Force and ICE for the company’s Azure cloud-computing service. Keane touted Azure’s ability to help the agency handle "sensitive unclassified data" and use tools such as facial recognition and identification. "The agency is currently implementing transformative technologies for homeland security and public safety, and we’re proud to support this work with our mission-critical cloud," Keane wrote in the post.

As of Monday morning, the portion of the post mentioning ICE was missing...''
https://www.bloomberg.com/news/articles/2018-06-18/microsoft-removes-mention-of-cloud-work-for-ice-after-protests

more:

https://searx.me/?q=24%20January%20Tom%20Kaene&categories=general&time_range=month&language=en-US

**Comment by PaulFree14** [comment]
>But most of us definitely would stand up to defend humanity, not just by moving data from a platform to another.

I'm not wanting to define for others what strategy to choose to stand up against fascism. But my proposal was definalty not about moving data from one plattform to another. 

I proposed to use this significant current event to take action through several forms. 
It could be even a strike during which the project leaves a statement for what reasons they are doing so.

**Comment by PaulFree14** [comment]
'...but that's all just symbolic and doesn't change anything.'

No. It has a clear potential of damaging microsofts investment in github and their brand as a whole. It can send a clear message to those wanting to make a profit from this violence. It is also supporting workers within microsoft who have positions against microsoft support of ICE, since it is stregning their position. 
Making microsoft to step out of ICE contract sends a clear message to those taking direct part in ICE. Right now, microsoft helps them with moral support and support in being legitimate institution.

**Comment by cmmata** [comment]
@PaulFree14 so I suppose you don't (ever) use Microsoft own products and services like Windows, Office, Outlook.com, Wunderlist, LinkedIn, Azure cloud, VS Code, Skype, Xbox and Microsoft games, and many others...

And also don't use any opensource project where Microsoft contributes like Linux kernel, or any service hosted in Azure platform.

If not, I honestly think that moving away from Github is useless.

Anyway I'm with @annando, it would be better to ask and talk in a polite and open posture, rather than saying that anyone who doesn't move away from Github is ok with fascism. It's not always black or white, there are a lot of greys.

**Comment by PaulFree14** [comment]
>I suppose you don't use Microsoft own products and services

I suppose of moving towards this. I'm not not aware of me using beside github any microsoft product. I miss nothing. 
But of course I know that it's not possible for everyone or even usefull in any situation. 

>If not, I honestly think that moving away from Github is useless.

That's the inviting the logic of, be entire radical or it's anyway worthless. And while we can't be entire radical let's just move on. 
And I heaviliy disagree with that. 

Is can you make an argument that is countering what I've wrote here, since you haven't ablied any logic that is proofing mine being wrong. Thought the logical fallacy you ablied here is called whataboutism (I might be wrong on this)

this one I ment:
'It has a clear potential of damaging microsofts investment in github and their brand as a whole. It can send a clear message to those wanting to make a profit from this violence. It is also supporting workers within microsoft who have positions against microsoft support of ICE, since it is stregning their position.
Making microsoft to step out of ICE contract sends a clear message to those taking direct part in ICE. Right now, microsoft helps them with moral support and support in being legitimate institution.'
...there's even more to say, but thought that's enough of an argument. 


>it would be better to ask and talk in a polite and open posture

yes that might be true. The culture I'm comming from understands the initial issue I wrote as polite and open posture. 
The answer I resieved as very unpolite, dominant, closed posture...
So I adopted my tone to it. 
But thought the tone shouldn't be much of a matter here, but rather the argument behind. Using it as an argument is known as tone policing:
'Tone policing (also tone trolling, tone argument and tone fallacy) is an ad hominem and antidebate appeal based on genetic fallacy. It attempts to detract from the validity of a statement by attacking the tone in which it was presented rather than the message itself' -wiki

>...rather than saying that anyone who doesn't move away from Github is ok with fascism.

(that's part of the tone policing)

I didn't. I said and still hold this up, complicit. In case I'm using this word wrong, or different then ppl are used to:

One can be against fascism while still having thirten behaviours that is supporting it, and by that being complicit in some aspects. So as you said, it's not just black and white. 

It was also used in relation of the disource here:

- me pointing out opressive behaviour ppl have an issue with, that is done by a company behind the plattform that is also used for twidere to collaborate on code
- mariotaku direct respond to it, stating it's unrelevant spam, calling to report me if I do it again and closed it

**Comment by cmmata** [comment]
> If not, I honestly think that moving away from Github is useless.
Well, I don't mean to be necessary 100% radical. But I think that if you move away from Github, but continue using other Microsoft services or other services using Microsoft's cloud, your impact wouldn't be bigger enough to be a significant change to Microsoft. If Microsoft sees that everybody is moving away from Github, the next step would be selling it or directly shutting it down. I don't see Microsoft changing that kind of decisions just because one service is not making money or doesn't have enough users. If you want a company to change something to that level, people need to take action in almost all use cases they have rather than in a few. For example, Google cancelled a military contract because of a lot of protests and resignations of their own employees, not because the end users.

**Comment by PaulFree14** [comment]
>If you want a company to change something to that level, people need to take action in almost all use cases they have rather than in a few.

I don't believe that. But also if true, it anyway makes sense to turn against any of their products and it isn't any counter argument to what I've stated. If I need to plant 10 seeds to have enough plants to eat, it still starts with planting one. 

They reseave already public pressure, also internal by their workers. Doing an action on github is just one part of it. 
If that doesn't make microsoft to change their desicion, their can be still many that are changing their decision of using microsoft and by that having impact on the longterm. 

>For example, Google cancelled a military contract because of a lot of protests and resignations of their own employees, not because the end users.

It's usefull to help the employees strenghening their positions. If they couldn't win it through the moral arguments alone, economic reasoning can help, and so can the enduser. 
Also protests and endusers do have an impact on the employees themself. They can be motivational for the employees to take action within their company. 

>But I think that if you move away from Github,...

also remember that I'm not calling for simply moving away. *I'm calling to use github for antifascist action.*

...and this is even not just about microsoft. 
Imagine many projects on github start to strike for some days and using it during that time to discuss, share research, publish statements about microsoft, their involvment in ICE, but also about the freedom of movment, open society etc. 

That can have a significant impact. But it's all a question if some projects will start and inspire other by it.

**Comment by PaulFree14** [comment]
>it would had been better to simply ask in a polite way - without any activism - if this projects considers moving to some other repository.

I don't understand why I should ask something else then that what I want to know. 

Just to make this very clear:

I'm asking if people are willingly to resist the violence that is conducted by ICE with support from micosoft, the company behind github. 

This polite thing is in general confusing me. Can someone point me where my initial issue is conflicting with it?

**Comment by orithena** [comment]
After reading this whole thread... I suppose it comes down to this:

Where do you draw the line?

Following the original premise consequentially would mean to denounce every entity that did trade with a "bad guy". One cannot do that. (Yes, I know that this looks like a slippery slope argument, but I'm arguing that everyone has their own line where their slippery slope starts.)

The premise begs for fallacies because there is no right way out. Either the argument devolves into whataboutism or into the slippery slope argument. It is an exemplary tool to divide a community that found together on completely different aspects.

@mariotaku chose his line. Let him. If you disagree, it just means that his line is drawn on less indirect constellations than yours.

@PaulFree14: Please reconsider your argument about "that is polite tone in the culture you come from". I know that tone to be prevalent in german Antifa circles. I'm german, I'm anti-fascist, and my biggest gripe about the Antifa circles is that their reasoning often implies "If you're not with me/not following my argument and conclusion, then you're against me!" -- and this is what your original post implies (at least to my understanding).

Now, with that in mind, please imagine @mariotaku on the other side of the world, minding his own problems stemming from the politics in his own country and having his own cultural education about what is polite and what not. I presume that his feel about your original post was like someone suddenly breaking down the door of his room and screaming "AGREE WITH ME AND DO AS I SAY OR YOU'RE MY ENEMY FOREVER BECAUSE OF POLITICS ON THE OTHER SIDE OF THE WORLD!"

I'm exaggerating here, of course, but please reconsider your view on the backlash to your proposal. I'm not surprised that @mariotaku reacted like he did.

Please try to establish in your culture that this is no polite way to present an argument. The way I see it, you run into the risk of hardening the opinion towards the opposite side, because people outside your cultural circle feel pressed into defensiveness when confronted with that line of reasoning. And defensiveness creates and hardens arguments opposite your intentions. (This argument is presented by my knowledge from that one university course on Social Psychology that I visited.)

Oh, yes, I'm derailing here with the second half of my post. It is meant as food for long-term thoughts for @PaulFree14; I don't even want an answer on that. Please consider both parts separately.

**Comment by PaulFree14** [comment]
thx @orithena for this reply. I read and ment my initial post definatly very different. 
Even reading it again (initial post), I simply can't understand where ppl see it as unpolite or understanding it as 'be with me or against me'. 
But some ppl gave now similiar feedback, so I gonna reflect on what went wrong between me writing the message and the resievers. 

>but please reconsider your view on the backlash to your proposal.

thx for that hint. On the same wanting to point this the other way, cause of the 'irrelevant spam' reply on a topic that highly emotional charged. 

>defensiveness creates and hardens arguments opposite your intentions.

Not nessasary. I think the phenomen you're mentioning here is called 'backfire effect'. 

''The Misconception: When your beliefs are challenged with facts, you alter your opinions and incorporate the new information into your thinking.

The Truth: When your deepest convictions are challenged by contradictory evidence, your beliefs get stronge''
https://youarenotsosmart.com/2011/06/10/the-backfire-effect/

>Following the original premise consequentially would mean to denounce every entity that did trade with a "bad guy"

I understand where you're argument of 'where to draw the line' is comming from. Everyone has to draw it for themself. I draw it somewhere else then others. Others draw them somewhere else then me. And that's even good. 
And that's not contradicting with my initial statement. Following my initial statements does not mean to do all at one. It's more about keeping current events in mind and aplying to them usefull strategies. 
Not simply mine, but multible with everyone making their own choices. 
So it's not contradicting with people having different lines, which is what your statement is based on. (if I understood it correct)
With what it is contradicting and where it makes a hard line is, that 
'giving value to institutions that are complicit in supporting forced mass detention etc. is bad'
That is the core argument after passing it through Occam's razor. 

I don't see any argument being made why it should be from here about weather whataboutsim or slipperslope since there is obviously also the option of: yes, this statement is true until a contradicting logical argument can be made. 

From this point it could be then rather about disagrement about the aplied strategy..etc.

In short meaning, you've limited the available options and formed your reasoning based on those, that are obviously both shitty options, that then formed an argument looking as it contradicts mine. 
(if one can remember the name of this fallacy I'd be interested in)

>@mariotaku chose his line. Let him.

Just in case it looks as I'm continue to argue here for the sake of making mariotaku changes their position, I'm not. 

It's for the reason of other devs. that might read this thread, and to find out what's wrong/should be better about my initial message since I still believe it is something that can be done with little efford and still be a meaningfull resistance against ICE and microsoft, mostly caused by the circumstances such as:
- there is already great outrage
- microsoft employees take positions against the ICE deal
- microsoft just bought github for 7.5 billion $ 
- microsoft being behind github is unpopular by many opensource devs. 
- there are free software alternatives to github that funtion great
- microsoft tried to hide their ICE involvment
