### ISSUE TITLE
Current version not available in F-Droid-Store

### ISSUE THREAD

**Issue by Krawei** [TwidereProject/Twidere-Android#1218]
Dear team,

when I take a look in the Google Playstore, the app's current version is 3.7.8, in F-Droid the current version is 3.7.6 .

What's the reason for this difference? Is there a bug in the building process? Please fix that.

Kind Regards,

Krawei

**Comment by Krawei** [comment]
Is there any progress here? Could you please give a commend regarding the status of my issue?

**Comment by kuba-orlik** [comment]
I'd also like to know that

**Comment by orithena** [comment]
I'm surprised that this issue isn't closed by now, because I've got version 3.7.8 from F-Droid (which has been there for seven months now, according to the F-Droid app).

Such discrepances are pretty normal, because Google publishes new versions immediately unless there is an immediate reason not to publish. On F-Droid, each new version undergoes a manual review done by volunteers (to check whether non-free libraries or trackers have been added), which considerably decelerates the publishing process. So F-Droid is not that fast to update, but the possibility of a rogue coder adding some unwanted stuff with a new version is way lower.

**Comment by pubmania** [comment]
@orithena - I can only see 3.7.6 on F-droid and no 3.7.8. How have you managed to get 3.7.8?
![Screenshot_20200316-071513_F-Droid](https://user-images.githubusercontent.com/1966557/76731711-f9db4780-6755-11ea-86cf-a3749c5f3cb2.jpg)

**Comment by Tedko** [comment]
@Tlaster Let's bring it back to FDroid

**Comment by Anglodel** [comment]
Same here… Hmm the last version, 4.0.4, released today, is of course not available yet in F-Droid, but versions 3.7.7+ are not available either.
(3.7.7, 3.7.8, 4.0.x)

**Comment by polyzen** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/1752
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6445

**Comment by Tedko** [comment]
Thats weird @mariotaku

**Comment by Tedko** [comment]
> Same here… Hmm the last version, 4.0.4, released today, is of course not available yet in F-Droid, but versions 3.7.7+ are not available either.
> (3.7.7, 3.7.8, 4.0.x)

Seems like F-Droid is not fetching updates on `maintain` branch. maybe we have to merge it to master. @Tlaster

**Comment by pubmania** [comment]
I I have been now able to upgrade on Android to 4.0.4 so looks like this issue can be closed. Thanks everyone. :)

**Comment by Tedko** [comment]
Thx
