### ISSUE TITLE
Drop Support for Android 4 and 5

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [TwidereProject/Twidere-Android#1347]
IF there aren't a lot of Android 4/5 users using Twidere then stop supporting them. Focus on Android 6 and above only.

**Comment by Tedko** [comment]
![Screen Shot 2020-08-06 at 21 07 34](https://user-images.githubusercontent.com/6687437/89535541-21c46800-d829-11ea-9437-6e59eab94a53.png)
![Screen Shot 2020-08-06 at 21 07 45](https://user-images.githubusercontent.com/6687437/89535546-22f59500-d829-11ea-944c-e71fc7b5c546.png)

We will consider drop <4.4 . @Tlaster  what do you think

**Comment by roytam1** [comment]
What does this Statistics based on? From Google Play? From F-Droid? or from twidere internal reporting?

**Comment by Tedko** [comment]
gplay

**Comment by Tedko** [comment]
I guess we should drop Android 4/5 any way. @Tlaster lets do it

**Comment by roytam1** [comment]
> 
> 
> gplay

then the statistics is incomplete.

**Comment by Tlaster** [comment]
I'm planning to drop support for Android 4.x in the brain new TwidereX since some of the major toolkits require Android 5.0+ (like Jetpack Compose).
And there's no promise that Android 5.x devices will run well as expect since my Nexus 5 was dead a couple of weeks ago so there's no physical device that I can test on.
