### ISSUE TITLE
Opening images full-screen fails since 0.3.0 (dev 2015-09-20)

### ISSUE THREAD

**Issue by blinry** [TwidereProject/Twidere-Android#222]
The preview works, but when trying to open an image full-screen, I get this Toast: "Error: Unknown error, this is probably a bug." and a black screen.

I can't find anything suspicious in logcat:

    I/ActivityManager(  550): START u0 {act=org.mariotaku.twidere.VIEW_MEDIA cmp=org.mariotaku.twidere/.activity.support.MediaViewerActivity (has extras)} from uid 10090 on display 0

**Comment by mariotaku** [comment]
Hi, this bug is caused by wrong image downloader and file cache code. Newest update (2015-10-10) may help

**Comment by blinry** [comment]
Yep, thanks!

**Comment by blinry** [comment]
Annnd… the error is back. (Version 2015-10-30.)

**Comment by mariotaku** [comment]
@blinry I tried but found nothing problem here. Could you provide some example and some details like your OS version?

**Comment by blinry** [comment]
It occurred on a Nexus 4 with a stock Lollipop 5.1.1. I just switched to Canogenmod 12.1, and the error's gone. I'm closing this until someone else can reproduce.

**Comment by orithena** [comment]
It's not completely gone, but crops up on my phone under different circumstances: Nexus 5, stock Android 5.1.1, no automatic media previews, patchy mobile connection capped to GPRS speed (not unusual in germany because of crappy mobile contracts), and not enough patience. In this scenario, when I view the timeline and tap a link to a image, it opens full screen; then it takes too long to load, so I tap "back" and read more of the timeline. Still being interested in that image, I go back and tap that link again, opening the black canvas for the image. After 1 or 2 seconds, the loading animation stops and the "Unknown Error, it may be a bug" crops up. The only way to view the image then is to open the tweet and tapping on the media preview.

I feel it's a problem of an improperly closed connection that is tried to be reused. In the past, this also came up when the mobile connection got lost while loading an image (instead of the user stopping it loading).
