### ISSUE TITLE
Implement activities by friends tab

### ISSUE THREAD

**Issue by mariotaku** [TwidereProject/Twidere-Android#368]

**Comment by mariotaku** [comment]
`activity/by_friends` was removed by twitter.

**Comment by RicardoGuzmanVelasco** [comment]
TweetDeck still providing tab with all friends' activity: favorites, new followings, new listed, etc. Any way to resume this?

**Comment by Adzetko** [comment]
I'm dedusting this thread, as the Twitter's like feature is far more used (at least by the people I follow) than RT, I have an activity tab in Tweetdeck as a "secondary" timeline, because I like to see what my followings are liking and things like that, I also like the fact it's another column from the main timeline in Tweetdeck (yeah official Twitter app is horrible at showing random likes in my timeline).
I would love to see a feature like this in Twidere.
