### ISSUE TITLE
Sorry if I am being dense, but...

### ISSUE THREAD

**Issue by muamma** [TwidereProject/Twidere-Android#426]
... I see all these version releases on https://github.com/TwidereProject/Twidere-Android/pulse, but F-droid stays stubbornly not offering me updates (on 3.0.6.1 at moment).

Does it take time for releases to filter through to F-droid?

Or is there some other way of installing new versions?

If this is a really stupid question, my apologies!

**Comment by mariotaku** [comment]
F-Droid checks for `master` branch, once merged to `master`, F-Droid will do their job, which is not part of my business.

If you want to try new versions, you can find in GitHub releases, but since they're signed by me, you'll need to uninstall F-Droid one first. I asked if they can publish APKs built by me also, seems still need to wait.
