### ISSUE TITLE
BUG: Tweet not possible - wrong character count

### ISSUE THREAD

**Issue by wnabernik** [TwidereProject/Twidere-Android#587]
Twidere Version 3.1.12 with Twitter for Android API-Keys:

I wanted to create a tweet with an Image - first uploaded the Image, wrote the Text - it used 136 chars, 4 are left (says Twidere).

Wanted to send it - tweet not possible.

Made the same procedure in Twitter Webclient: 180 chars used, 40 over the limit. Deleted the Image, then I had my 136 chars.

Somehow Twidere doesn't count the chars needed for the Image.

In previous Versions (latest working was IIRC 3.1.9) this was not a problem (Images - the URL - where counted correct, and I could get to the max. 140 chars)

**Comment by orithena** [comment]
Looks like @mariotaku already implemented some to-be-changed character count rules (see #556), but Twitter isn't ready yet. I expect that this issue will resolve itself as soon as Twitter actually enables the new rules on their servers.

**Comment by wnabernik** [comment]
@orithena yeah, I read that (also the linked description from Twitter), and was very suprised (because Twitter wrote in their docu that Web client should have the new rules first) that I was over the limit there. Maybe it's possible to implement the old routine and enabling it as legacy option (marked to be removed till Twitter enrolled their new rules to all their Server (and own clients - Tweetdeck for example counts also within the "old" way).

**Comment by orithena** [comment]
@wnabernik The new rules aren't rolled out yet, not even in Twitter Web. There's no good way to handle this situation; either way, you get complaints. Either because someone wonders beforehand (like you), or someone wants the feature NOW as soon as it makes it's round on Twitter or because someone did not see the option in the preferences (which is, coincidentally, the most hassle in terms of coding and not worth to do just for an intermediary time span).

I'd say it's better to err beforehand. Least complaints (only acute users like you even spot it) and the feature is usable as soon as it's rolled out on the servers.

Therefore, technically, I'd call this a non-issue, waiting for it to resolve itself.

**Comment by pseudomonas** [comment]
I think this *is* an issue, and the switch should be flipped only when needed (either by the user or by the maintainer)

**Comment by mariotaku** [comment]
Now this was fixed in 3.2.5.

I added a feature to let Twidere get remote config, media link will be counted by default, but when Twitter really rolls new mechanism out, I'll push a new config so all previous versions will work correctly.

**Comment by orithena** [comment]
@mariotaku The switch is due on Sept. 19th -- see http://www.theverge.com/2016/9/12/12891562/twitter-tweets-140-characters-expand-photos

**Comment by mariotaku** [comment]
Thanks, as soon as I push config change, it will be available with in 12
hours.

Dave <notifications@github.com>于2016年9月14日周三 00:28写道：

**Comment by orithena** [comment]
I just noticed that the official client now stopped counting reply mentions at the start of a tweet. Looks like it's time for the next config push, @mariotaku :D
