### ISSUE TITLE
Getting to the end of a list does not load in more tweets

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#596]
This is the same issue as #369, but has reappeared in the recent releases. Possibly to do with the way tweets have been rearranged.

**Comment by borekb** [comment]
I can confirm this. It's one of the more annoying issues because when I'm reading Nth page of tweets in a list and it refuses to load more, I need to go out and back again which takes me to the beginning of the list.

Ideally, I'd like if Twidere attempted to load more automatically but if that fails, swipe up would be the manual way to load more.

**Comment by borekb** [comment]
I think it does this in the recent update (3.4.22), thanks @mariotaku!

**Comment by DrustZ** [comment]
To anyone coming here: twitter itself sometimes only include certain tweets after a time period of the accounts in a list. So if you cannot load more tweets in the list page, it's from the api side (you can verify it on twitter.com).
