### ISSUE TITLE
"Load more" sometimes is missing between tweets

### ISSUE THREAD

**Issue by orithena** [TwidereProject/Twidere-Android#650]
I noticed that in some cases I cannot read everything on a list tab, because the "load more" button is missing in between new and old tweets...

It may be hard to reproduce, so here are all points I can think of that might play a role:

 * It only happens after some hours of not using Twidere (e.g. after I was sleeping)
 * My list in question is active: It produces more tweets than my "load at once" setting during my sleep hours (in other words: I set Twidere to load in chunks of 50 tweets; this list produces ~120 tweets while I sleep... which would lead to me missing about 70 tweets).
 * I have the "remember position" and "read from bottom" Twidere settings active.
 * I have deactivated any automatic update (except for interactions), so this list tab is only updated manually.

(I noticed on Twidere 3.3.9 and 3.2.9)

**Comment by pm2kjiagm** [comment]
This problem can be reproduced almost every time in my environment.
这个问题目前在我的环境下几乎可以100%复现。

**Comment by gena01** [comment]
Actually this has gotten worse in recent releases. I have it set to load 200 at a time. After 2 or so "load more"s it stops and won't load anymore. This used to work before.

**Comment by mariotaku** [comment]
@gena01 Where did you get this problem, home/interactions timeline or custom timeline?

**Comment by mariotaku** [comment]
@gena01 If you getting "Can't load earlier tweets" on some gaps older than ~4 hours, then it was caused by Twitter's 800 tweets limit.

**Comment by gena01** [comment]
@mariotaku i am getting it in the home timeline. Twittnuker works fine though and is able to load more tweets than Twidere.

**Comment by mariotaku** [comment]
@gena01 Which problem do you get, gap disappeared or "Can't load earlier tweets"?

**Comment by morinap** [comment]
@mariotaku It's not limited to home timeline as I observe the problem (the gap disappeared) in a tab containing a list timeline.

**Comment by mariotaku** [comment]
@morinap Home timeline/interactions should work fine now, while list timeline sometime still have this problem which is harder to tackle.

**Comment by fishy** [comment]
I'm still seeing this problem on v3.7.3.

Usually when I wake up in the morning there are ~120 new tweets in my home timeline. If my "Load item limit" is set to 20 (default value), after 2 or 3 load mores (3 or 4 loads including the initial auto load as I turned on "Refresh on start") it won't load anything more and the "load more" button disappears, but there are certainly a gap there.

If my "Load item limit" is set to 50, it's usually fine.

Another problem related is the unread count on the home tab. Let's say you have "Load item limit" set to 20 and "Refresh on start" turned on, and there are 30 new tweets since you last load. After you open Twidere it will auto refresh the newest 20 tweets, and the unread count will be 20 and there's load more. After you clicked load more, the rest 10 tweets will be load, but the unread count is still 20. The unread count should become 30 after load more.

**Comment by Tedko** [comment]
@fishy  - can you try twidere 4.1.x and see if this problem still exists?

**Comment by fishy** [comment]
@Tedko I believe it's fixed. I'm not seeing this recently.

**Comment by Tedko** [comment]
Thanks for the info!
