### ISSUE TITLE
Swipe down doesn't work

### ISSUE THREAD

**Issue by Hylak** [TwidereProject/Twidere-Android#726]
## Expected behavior
Go to my profile and see tweets, likes and media.

## Actual behavior
See swipe down to refresh, do it, and nothing happens.  Not even the refreshing animation.

## Steps to reproduce
Go to my profile, refresh swiping down, nothing happens.

## Extra info

Android version: 5.02

Network type:

- [x] Cellular
- [x] Wi-Fi

App version: Up to date on the store (3.4.22)

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [x] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

PS: sorry, I send it before completing it by mistake. Now it's done.

**Comment by orithena** [comment]
Please provide more context. The form actually is there to be filled in. The developers need to know your Twidere and Android version and a description of how to reproduce the problem... because: swipe down normally does work on my device on all tabs.

**Comment by Hylak** [comment]
Sorry, I missed some fields.

The point was to know if this was a general issue or a device related issue. Reading your comment I guess it's the latter.

There isn't much to say, there's the message to "swipe down to refresh" where the tweets should be when you look at your profile. I try to swipe down, but anything happens. On my timeline and tabs it works, it appears the loading animation circle and loads the new tweets/notifications, but it does happen nothing in the profile.

**Comment by orithena** [comment]
Ah, the context "profile view" was the point. In this case I can confirm this.

Swiping down to refresh a profile does not seem to be implemented or does not work (Twidere 3.4.22-google, OS: stock Android 6.0.1, device: Nexus 5, official API keys). It does not matter whether I view my own profile or someone else's profile; even when there was a timeout due to bad network connection I cannot refresh the profile.

I'd mark this issue as a feature request since I cannot remember if this was possible at all at some point.
