### ISSUE TITLE
[Feature Request] Automatic Selection of Corresponding Account within 'Settings > Tabs' When User Switches From One Account to Another.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [TwidereProject/Twidere-Android#733]
I operate more than one account via Twidere. When I switch between them, I have to manually change the accounts in Settings > Tabs every time in order to see the relevant Timeline, Interactions, etc. After a while, this gets tedious.

I'd like to see Twidere making this change automatically for users when they switch between accounts. 

Thank you.

PS: Feel free to rephrase the subject.

**Comment by orithena** [comment]
Umm... I might've misunderstood your request and/or situation, but I think you could solve this by creating multiple timeline/interactions/etc tabs, one for each account. Changing the account in the sidebar currently only applies to the views opened from the sidebar. One tab is tied to one account, but you can create multiple tabs of the same type in Settings > Tabs.

If that does not solve the tediousness (granted: in a slightly different way than you expected/requested), then I'm at a loss as to what you're referring to (and I assume that the main developer would be, too), because it really differs from my experience with Twidere. Could you please elaborate further, then?

**Comment by mariotaku** [comment]
@iknownothingaboutcomputers Some tab has **immutable** account configuration, since they relies heavily on account information, thus can't be changed once created.
