### ISSUE TITLE
Cannot Delete DM.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [TwidereProject/Twidere-Android#933]
A week ago I sent a DM to a company but never got a reply from them. Therefore, I want to delete that useless thread now but Twidere won't let me. Is it a bug?

Using Android 5.1.

**Comment by orithena** [comment]
It's not a bug that I know of. I can delete DMs just fine, using Twidere 3.6.24 (from Google Play) on Android 6.0.1.

Knowing Twitter and their protocol a bit (I'm not a Twidere developer), the answers to the following questions might help to nail down whether it's a bug in Twidere (and where it is):

* Does that DM show up in the Twitter Web interface?
* Can you send DMs to that company from the Twitter Web interface? 
* If yes, can you delete that DM from the Twitter Web interface?

If you can answer yes to all three questions, it might be a bug in Twidere in the DM deletion part. If you answer the first question with no, it might also be a bug in Twidere, but in the "DM sending and error handling" part of Twidere. In any case, the following information might also be helpful (yes, I know, some of them are not easily checkable, just answer them to your best knowledge):

* Do you follow that company's account?
* Does that company's account follow you?
* If not (to any of above), do they accept DMs from everyone? Also, do you accept DMs from everyone?
* Is that company's account disabled/suspended/deleted by now? I.e. did the status of that account change since sending that DM?
* Which version of Twidere are you using? (Settings -> scroll the icon bar down -> the icon with the circled 'i')

**Comment by iknownothingaboutcomputers** [comment]
@orithena @mariotaku Terribly sorry about this late reply.

1. No.

2. Yes, I can send DM to that company from Twitter Web Client.

3. Yes. In fact, I already deleted it from Twitter Web Client. But it still appears in the Twidere app.

***

1. No. (But I've added them to a list, if that matters).

2. No.

3. Yes. In fact, after reading your reply, I sent another DM to them from Twitter Web Client and they replied to it. So yes, they do accept DMs from everyone. Deleted the DM again soon afterwards in TWC but still appears in the app. As for me, no, I do not accept DMs from everyone.

4. The status of that company's account is very much active.

5. I'm using Twidere 3.6.24, downloaded from F-Droid.

Once again I'm really sorry for this super late reply.

Thank you.

**Comment by orithena** [comment]
This has got the hallmarks of "Twidere tries to delete a not-anymore-existing DM and does not interpret the resulting error code correctly".

Also, I'm a bit surprised that this company could answer your DM when you don't accept DMs from everyone. Looks like Twitter updated DM handling in a way that's more consistent with users expectations, but I wasn't aware of it yet.

**Comment by orithena** [comment]
Oh, another question, @iknownothingaboutcomputers: Does that deleted DM go away when you update DMs (by pulling down in the DM overview screen until the loading indicator appears)? (Additional info for @mariotaku: I just noticed that DMs of accounts I blocked don't go away when I do that... they do go away in the official Android Twitter App, though.)

Anyway, thanks for clarifying. Up until that, I was under the impression that you deleted that DM from Twidere.

**Comment by iknownothingaboutcomputers** [comment]
@orithena @mariotaku No, that DM doesn't go away even after pulling down in the DM overview screen.

***

Not sure if questions can be posted as issues so I'll just ask it here: Is my real IP address revealed to Twitter even if I use the Twidere app with a VPN?

**Comment by orithena** [comment]
Okay, I can't think of any more info that might help @mariotaku to find that issue, so let's just hope he finds it.

To answer your other question: It really depends on the settings for that VPN. If it is set to "redirect all network traffic via VPN" (as opposed to "redirect only traffic intended for the internal network of company X") _and_ that VPN uses a router that does Network Address Translation (i.e. masking the VPN-internal address of that user), _then_ Twitter will only see the VPN router's IP address.

You could check that by visiting websites like http://whatismyip.com, once with VPN active and once with VPN inactive. If the website reports different IP addresses for each try, Twitter too can't see your real IP address if you're logged in via VPN.

There'd be an exception to that rule, which applies if the VPN client is not a real VPN Client and just sets a proxy for the browser. In this case you'd be better off if you simply configure Twidere itself to use that proxy.

**Comment by iknownothingaboutcomputers** [comment]
Thank you.

**Comment by mariotaku** [comment]
I think it's a lack of feature in Twidere, "Delete messages and remove conversation" feature will be added (for non-official keys) soon.

**Comment by iknownothingaboutcomputers** [comment]
@mariotaku @orithena Updated Twidere from F-Droid (version 3.6.29) and I don't see that DM anymore. Hurray! Issue resolved! Thank you very much. :)
